name: emg3d-gallery

channels:
  - conda-forge
  - defaults
dependencies:
  - emg3d
  - joblib
  - matplotlib
  - memory_profiler
  - pip
  - pymatsolver
  - scooby
  - simpeg
  - sphinx
  - sphinx-gallery
  - numpydoc
  - sphinx_rtd_theme
  - pyvista
  - pip:
    - gempy
    - nptyping
    - sphinx_numfig
